import type { Metadata } from "next";
import { Inter } from "next/font/google";
import FeatherIcon from "feather-icons-react";
import DashboardLayout from "../../components/DashboardLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <DashboardLayout
      sidebarLinks={[
        {
          url: "/dashboard",
          icon: <FeatherIcon icon="home" />,
          label: "Dashboard",
        },
        {
          url: "/dashboard/products/list",
          icon: <FeatherIcon icon="package" />,
          label: "Products",
        },
        {
          url: "/dashboard/orders/list",
          icon: <FeatherIcon icon="package" />,
          label: "Orders",
        },
        {
          url: "/dashboard/users/list",
          icon: <FeatherIcon icon="package" />,
          label: "Users",
        },
      ]}
    >
      {children}
    </DashboardLayout>
  );
}
